import os
import secrets
import time
from typing import Dict, Optional, Tuple
from urllib.parse import urlencode
import httpx
from fastapi import HTTPException, status


class GoogleOAuthService:
    """
    Production-grade Google OAuth 2.0 / OpenID Connect service.
    Implements standard Authorization Code flow.
    Supports secure state validation against CSRF.
    """

    GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
    GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
    GOOGLE_USERINFO_URL = "https://openidconnect.googleapis.com/v1/userinfo"

    def __init__(self):
        self.client_id = os.environ.get("GOOGLE_CLIENT_ID", "")
        self.client_secret = os.environ.get("GOOGLE_CLIENT_SECRET", "")
        self.redirect_uri = os.environ.get(
            "GOOGLE_REDIRECT_URI", "http://localhost:8000/api/auth/google/callback"
        )
        self.frontend_url = os.environ.get("FRONTEND_URL", "http://localhost:5173")
        # In-memory store for state nonces: {state: expiry_timestamp}
        self._state_store: Dict[str, float] = {}

    def is_configured(self) -> bool:
        """Returns True only if all required Google OAuth credentials are present."""
        return bool(self.client_id and self.client_secret and self.redirect_uri)

    def generate_state(self, ttl_seconds: int = 600) -> str:
        """Generates a cryptographically secure state parameter with TTL."""
        self._purge_expired_states()
        state = secrets.token_urlsafe(32)
        self._state_store[state] = time.time() + ttl_seconds
        return state

    def validate_state(self, state: Optional[str]) -> bool:
        """Validates that the returned OAuth state was generated by this server and has not expired."""
        if not state:
            return False
        self._purge_expired_states()
        expiry = self._state_store.pop(state, None)
        if expiry is None:
            return False
        return time.time() <= expiry

    def _purge_expired_states(self) -> None:
        now = time.time()
        expired = [s for s, exp in self._state_store.items() if exp < now]
        for s in expired:
            self._state_store.pop(s, None)

    def get_authorization_url(self, state: str) -> str:
        """Constructs the real Google sign-in authorization redirect URL."""
        if not self.is_configured():
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="Google OAuth is not configured on this server.",
            )

        params = {
            "client_id": self.client_id,
            "redirect_uri": self.redirect_uri,
            "response_type": "code",
            "scope": "openid email profile",
            "state": state,
            "access_type": "online",
            "prompt": "select_account",
        }
        return f"{self.GOOGLE_AUTH_URL}?{urlencode(params)}"

    async def exchange_code(self, code: str) -> dict:
        """Exchanges the authorization code for tokens with Google's OAuth server."""
        if not self.is_configured():
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="Google OAuth is not configured on this server.",
            )

        data = {
            "code": code,
            "client_id": self.client_id,
            "client_secret": self.client_secret,
            "redirect_uri": self.redirect_uri,
            "grant_type": "authorization_code",
        }

        async with httpx.AsyncClient(timeout=15.0) as client:
            try:
                response = await client.post(self.GOOGLE_TOKEN_URL, data=data)
            except httpx.RequestError as exc:
                raise HTTPException(
                    status_code=status.HTTP_502_BAD_GATEWAY,
                    detail=f"Failed to communicate with Google authentication server: {str(exc)}",
                )

        if response.status_code != 200:
            error_data = response.json() if "application/json" in response.headers.get("content-type", "") else {}
            error_msg = error_data.get("error_description") or error_data.get("error") or response.text
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Google OAuth token exchange failed: {error_msg}",
            )

        return response.json()

    async def get_user_info(self, access_token: str) -> dict:
        """Retrieves user profile and email identity from Google's OpenID Connect endpoint."""
        async with httpx.AsyncClient(timeout=15.0) as client:
            try:
                response = await client.get(
                    self.GOOGLE_USERINFO_URL,
                    headers={"Authorization": f"Bearer {access_token}"},
                )
            except httpx.RequestError as exc:
                raise HTTPException(
                    status_code=status.HTTP_502_BAD_GATEWAY,
                    detail=f"Failed to fetch user info from Google: {str(exc)}",
                )

        if response.status_code != 200:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Failed to retrieve identity from Google.",
            )

        data = response.json()
        sub = data.get("sub")
        email = data.get("email")
        if not sub or not email:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Google identity response missing required subject or email.",
            )

        return {
            "sub": str(sub),
            "email": str(email).strip().lower(),
            "name": data.get("name") or str(email).split("@")[0],
            "email_verified": bool(data.get("email_verified", False)),
            "picture": data.get("picture"),
        }


# Singleton service instance
google_oauth_service = GoogleOAuthService()
