"""Sync models for test db

Revision ID: e8957aeb5353
Revises: 2376fb822a1e
Create Date: 2026-09-11 21:20:57.967588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8957aeb5353'
down_revision: Union[str, Sequence[str], None] = '2376fb822a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    op.add_column('schemes', sa.Column('requirement_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'requirement_definitions')
    # ### end Alembic commands ###
